### ISSUE TITLE
Trace: { [Error: uncaught exception]

### ISSUE THREAD

**Issue by goofy79** [fvdm/nodejs-tk102#17]
Hello, 
i tried your server, but i get often this error ?

Trace: { [Error: uncaught exception]
  error: 
   { [Error: Socket error]
     reason: 'Socket error',
     socket: 
      { _connecting: false,
        _handle: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        onend: null,
        destroyed: true,
        bytesRead: 26,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1431944307470,
        _monotonicStartTime: 16494237665,
        pipe: [Function],
        addListener: [Function: addListener],
        on: [Function: addListener],
        pause: [Function],
        resume: [Function],
        read: [Function],
        _consuming: true },
     settings: { ip: '0.0.0.0', port: 5030, connections: 10, timeout: 10 } } }
    at process.tk102.createServer.tk102.settings.(anonymous function) (/srv/tk102-gw/daemon/tk102.js:79:11)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:301:26)

can you help me ?

**Comment by fvdm** [comment]
Can you post a code snippet of how you are using the module?

**Comment by goofy79** [comment]
I use it with you sample 

var server = require ('./tk102');

// start server
server.createServer ({
  port: 5030
});

// incoming data
server.on ('track', function (gps) {
  console.log (gps);
});

and with the tk102-gw (https://github.com/philcrump/tk102-gw)
but with both i get the same error.

**Comment by fvdm** [comment]
Hi, took a while but I think it may be fixed now. Could you please retry with `npm install fvdm/nodejs-tk102#develop`?
