### ISSUE TITLE
Support for TK103?

### ISSUE THREAD

**Issue by semireg** [fvdm/nodejs-tk102#21]
Will you consider support for TK103 units?

These were purchased from http://www.amazon.com/Real-Time-Portable-GPS-Tracker/dp/B001FYQO3W?ie=UTF8&psc=1&redirect=true&ref_=oh_aui_detailpage_o04_s00 and seem to use TK103, which is decodable by Traccar via port 5002. Follows format as listed in https://raw.githubusercontent.com/tananaev/traccar/master/tools/test-integration.py.

```
Incoming data: (027043828342BR00160419A4402.8913N09138.2201W000.60051110.000000000000L00000000)
{ [Error: Cannot parse GPS data from device]
  reason: 'Cannot parse GPS data from device',
  input: '(027043828342BR00160419A4402.8913N09138.2201W000.60051110.000000000000L00000000)',
  connection:
   { address: '0.0.0.0',
     family: 'IPv4',
     port: 1337,
     remoteAddress: '172.56.X.Y',
     remotePort: 37867 } }
Incoming data: (027043828342BP00000027043828342HSO)
{ [Error: Cannot parse GPS data from device]
  reason: 'Cannot parse GPS data from device',
  input: '(027043828342BP00000027043828342HSO)',
  connection:
   { address: '0.0.0.0',
     family: 'IPv4',
     port: 1337,
     remoteAddress: '172.56.X.Y',
     remotePort: 37867 } }
```

**Comment by fvdm** [comment]
I'm not sure, all my TK* trackers are bricked and I don't intent to by another one ever again...

At the moment I'm looking into the [Electron](https://store.particle.io/collections/electron) so I push clean JSON data to my server without all the trouble with those eBay trackers.

**Comment by semireg** [comment]
I would be interested in helping with an electron. I've been experimenting with the asset tracking kit. The form factor is a little large for my use case, though.

How'd you brick your tk?

Caylan

**Comment by fvdm** [comment]
Yeah that's why I'm still considering the Electron. It needs to fit waterproof inside a dog collar... (or size close enough)

**Comment by fvdm** [comment]
I bricked them simply by using them. Mostly indoors, no water contact, they just died on their own.
