### ISSUE TITLE
don't parse GPS data TK102b ! 

### ISSUE THREAD

**Issue by Dr-Lemon** [fvdm/nodejs-tk102#37]
Hello I buy a GPS tracker on Amazon but I did not expect it to be so complicated.

But we will say that we like it in the computer!

I followed launching in first demo.js and I simply received the IMEI of my tracker

```
Event: connection
{address: '0.0.0.0',
  family: 'IPv4',
  port: 1337,
  remoteAddress: '37 .171.230.59 ',
  remotePort: 63500}

Event: data
(087079484741BP00352887079484741HSOP47) '
DATA: (087079484741BP00352887079484741HSOP47)

Event: fail
{Error: Can not parse GPS data from device
    at Socket. <anonymous> (/root/gpsAl/node_modules/tk102/tk102.js:174:19)
    at emitOne (events.js: 96: 13)
    at Socket.emit (events.js: 188: 7)
    at readableAddChunk (_stream_readable.js: 176: 18)
    at Socket.Readable.push (_stream_readable.js: 134: 10)
    at TCP.onread (net.js: 559: 20)
  reason: 'Can not parse GPS data from device',
  input: '(087079484741BP00352887079484741HSOP47)',
  connection:
   {address: '0.0.0.0',
     family: 'IPv4',
     port: 1337,
     remoteAddress: '37 .171.230.59 ',
     remotePort: 63500}}
```

By analyzing the [issues](https://github.com/fvdm/nodejs-tk102/issues/22) I have therefore tried a resolution by adding a library "time-sleep" and using the exemple.js

By launching the code I received this:

`DATA(087079484741BR00190406V4314.0199N00533.1265E009.1190937000.00,00000000L00000000)`

I find it positive but I try by all means to decrypt this frame but I find only this [documentation](https://dl.dropboxusercontent.com/s/fjcqndpzhcqfwfh/KX402_GPRS_V15_EN.pdf) on the internet that does not bring me much.

it's been days that I'm looking for solutions help me!

**Comment by fvdm** [comment]
At the bottom of the document in your link the message format is described. To me it looks like this:

value | description
-|-
087079484741 | device id
BR00 | command word
190406 | date in YYMMDD
V | GPS fix: A = yes, V = no
4314.0199 | latitude in DMS
N | latitude North or South
00533.1265 | longitude in DMS
E | longitude East or West
009.1 | speed in km/h
190937 | time in HHMMSS
000.00 | orientation in degrees
, |
00000000 | IO state: first 0/1 = main power, second 0/1 = ignition
L |
00000000 | mileage meters in hex
